local function generateLocalizationTables(bossKeys)
    -- Ordenar claves alfabéticamente (case-insensitive)
    local sortedKeys = {}
    for k in pairs(bossKeys) do table.insert(sortedKeys, k) end
    table.sort(sortedKeys, function(a,b) return a:lower() < b:lower() end)

    -- Diccionario de traducciones específicas
    local translations = {
        [" the "] = " el ",
        [" of "] = " de ",
        ["Time-Lord"] = "Señor del Tiempo",
        ["Drifting Avatar"] = "Avatar Errante",
        ["Mossheart"] = "Cardomusgo",  -- Ejemplo de nombre traducido
        -- Añade más traducciones aquí
    }

    -- Generar tablas
    local output = "local AL = {\n    enUS = {\n"
    -- Tabla enUS (siempre true)
    for _, key in ipairs(sortedKeys) do
        output = output .. string.format('        ["%s"] = true,\n', key)
    end
    
    output = output .. "    },\n\n    esES = {\n"
    -- Tabla esES (con traducción)
    for _, key in ipairs(sortedKeys) do
        local translated = key
        -- Aplicar traducciones específicas
        for eng, esp in pairs(translations) do
            translated = translated:gsub(eng, esp)
        end
        output = output .. string.format('        ["%s"] = "%s",\n', key, translated)
    end
    
    return output .. "    },\n}"
end

-- Ejemplo de uso con tus datos
local originalBossKeys = {
    ["Core Hound"] = true,
		["Lava Surger"] = true,
		["Flame Imp"] = true,
		["Mad Servant"] = true,
		["Deathknight Cavalier"] = true,
		["Death Lord"] = true,
		["Doctor Weavil"] = true,
		["Ostarius"] = true,
		["Concavius"] = true,
		["Rotmaw"] = true,
		["Antnormi"] = true,
		["Mossheart"] = true,
		["Time-Lord Epochronos"] = true,
		["Drifting Avatar of Sand"] = true,
		["Epidamu"] = true,
		["Chronar"] = true,
		["Rookery Hatcher"] = true,
		["Rookery Guardian"] = true,
		["Sanctum Dragonkin"] = true,
		["Sanctum Dreamer"] = true,
		["Sanctum Supressor"] = true,
		["Sanctum Wyrmkin"] = true,
		["Sanctum Wyrm"] = true,
		["Solnius"] = true,
		["Erennius"] = true,
		["Dark Rider Champion"] = true,
		["Lord Blackwald II"] = true,
		["Phantom Servant"] = true,
		["Brood Queen Araxxna"] = true,
		["Grizikil"] = true,
		["Clawlord Howlfang"] = true,
		["Moroes"] = true,
		["Blackhand Incarcerator"] = true,
		["Venom Stalker"] = true,
		["Living Monstrosity"] = true,
		["Deathknight Captain"] = true,
		["Death Talon Wyrmguard"] = true,
		["Anubisath Sentinel"] = true,
		["Qiraji Brainwasher"] = true,
		["Qiraji Mindslayer"] = true,
		["Qiraji Champion"] = true,
		["Flesh Hunter"] = true,
		["Deathknight Captain"] = true,
		["Nerubian Overseer"] = true,
		["Avalanchion"] = true,
		["The Windreaver"] = true,
		["Baron Charr"] = true,
		["Princess Tempestria"] = true,
		["Grethok the Controller"] = true,
		["Patchwerk"] = true,
		["Grobbulus"] = true,
		["Gluth"] = true,
		["Feugen"] = true,
		["Stalagg"] = true,
		["Thaddius"] = true,
		["Anub'Rekhan"] = true,
		["Grand Widow Faerlina"] = true,
		["Maexxna"] = true,
		["Instructor Razuvious"] = true,
		["Deathknight Understudy"] = true,
		["Gothik the Harvester"] = true,
		["Highlord Mograine"] = true,
		["Thane Korth'azz"] = true,
		["Lady Blaumeux"] = true,
		["Sir Zeliek"] = true,
		["The Four Horsemen"] = true,
		["Noth the Plaguebringer"] = true,
		["Heigan the Unclean"] = true,
		["Loatheb"] = true,
		["Sapphiron"] = true,
		["Kel'Thuzad"] = true,
		["Lord Victor Nefarius"] = true,
		["Nefarian"] = true,
		["Vaelastrasz the Corrupt"] = true,
		["Razorgore the Untamed"] = true,
		["Broodlord Lashlayer"] = true,
		["Chromaggus"] = true,
		["Ebonroc"] = true,
		["Firemaw"] = true,
		["Flamegor"] = true,
		["Majordomo Executus"] = true,
		["Ragnaros"] = true,
		["Baron Geddon"] = true,
		["Golemagg the Incinerator"] = true,
		["Garr"] = true,
		["Sulfuron Harbinger"] = true,
		["Shazzrah"] = true,
		["Lucifron"] = true,
		["Gehennas"] = true,
		["Magmadar"] = true,
		["Onyxia"] = true,
		["Azuregos"] = true,
		["Lord Kazzak"] = true,
		["Ysondre"] = true,
		["Emeriss"] = true,
		["Taerar"] = true,
		["Lethon"] = true,
		["Dark Reaver of Karazhan"] = true,
		["Twilight Corrupter"] = true,
		["High Priestess Jeklik"] = true,
		["High Priest Venoxis"] = true,
		["High Priest Thekal"] = true,
		["High Priestess Arlokk"] = true,
		["High Priestess Mar'li"] = true,
		["Jin'do the Hexxer"] = true,
		["Bloodlord Mandokir"] = true,
		["Gahz'ranka"] = true,
		["Gri'lek"] = true,
		["Hazza'rah"] = true,
		["Renataki"] = true,
		["Wushoolay"] = true,
		["Hakkar"] = true,
		["Ayamiss the Hunter"] = true,
		["Buru the Gorger"] = true,
		["General Rajaxx"] = true,
		["Lieutenant General Andorov"] = true,
		["Moam"] = true,
		["Hive'Zara Soldier"] = true,
		["Anubisath Guardian"] = true,
		["Ossirian the Unscarred"] = true,
		["Lord Kri"] = true,
		["Princess Yauj"] = true,
		["Vem"] = true,
		["The Bug Family"] = true,
		["Eye of C'Thun"] = true,
		["C'Thun"] = true,
		["Anubisath Defender"] = true,
		["Anubisath Warder"] = true,
		["Fankriss the Unyielding"] = true,
		["Princess Huhuran"] = true,
		["Ouro"] = true,
		["Battleguard Sartura"] = true,
		["The Prophet Skeram"] = true,
		["Emperor Vek'lor"] = true,
		["Emperor Vek'nilash"] = true,
		["The Twin Emperors"] = true,
		["Viscidus"] = true,
		["Alzzin the Wildshaper"] = true,
		["Ambassador Flamelash"] = true,
		["Anger'rel"] = true,
		["Archivist Galford"] = true,
		["Atal'alarion"] = true,
		["Avatar of Hakkar"] = true,
		["Bael'Gar"] = true,
		["Balnazzar"] = true,
		["Baroness Anastari"] = true,
		["Baron Rivendare"] = true,
		["Cannon Master Willey"] = true,
		["Captain Kromcrush"] = true,
		["Celebras the Cursed"] = true,
		["Crystal Fang"] = true,
		["Darkmaster Gandling"] = true,
		["Doctor Theolen Krastinov"] = true,
		["Doom'rel"] = true,
		["Dope'rel"] = true,
		["Dreamscythe"] = true,
		["Emperor Dagran Thaurissan"] = true,
		["Fineous Darkvire"] = true,
		["Gasher"] = true,
		["General Angerforge"] = true,
		["General Drakkisath"] = true,
		["Gloom'rel"] = true,
		["Golem Lord Argelmach"] = true,
		["Goraluk Anvilcrack"] = true,
		["Guard Fengus"] = true,
		["Guard Mol'dar"] = true,
		["Guard Slip'kik"] = true,
		["Gyth"] = true,
		["Halycon"] = true,
		["Hate'rel"] = true,
		["Hazzas"] = true,
		["Hearthsinger Forresten"] = true,
		["The Unforgiven"] = true;
		["High Interrogator Gerstahn"] = true,
		["Highlord Omokk"] = true,
		["Hukku"] = true,
		["Hurley Blackbreath"] = true,
		["Hydrospawn"] = true,
		["Illyanna Ravenoak"] = true,
		["Immol'thar"] = true,
		["Instructor Malicia"] = true,
		["Jammal'an the Prophet"] = true,
		["Jandice Barov"] = true,
		["King Gordok"] = true,
		["Kirtonos the Herald"] = true,
		["Lady Illucia Barov"] = true,
		["Landslide"] = true,
		["Lethtendris"] = true,
		["Lord Alexei Barov"] = true,
		["Lord Incendius"] = true,
		["Lord Vyletongue"] = true,
		["Lorekeeper Polkelt"] = true,
		["Loro"] = true,
		["Magister Kalendris"] = true,
		["Magistrate Barthilas"] = true,
		["Magmus"] = true,
		["Maleki the Pallid"] = true,
		["Marduk Blackpool"] = true,
		["Meshlok the Harvester"] = true,
		["Mijan"] = true,
		["Morphaz"] = true,
		["Mother Smolderweb"] = true,
		["Nerub'enkan"] = true,
		["Noxxion"] = true,
		["Ogom the Wretched"] = true,
		["Overlord Wyrmthalak"] = true,
		["Phalanx"] = true,
		["Plugger Spazzring"] = true,
		["Postmaster Malown"] = true,
		["Princess Moira Bronzebeard"] = true,
		["Princess Theradras"] = true,
		["Prince Tortheldrin"] = true,
		["Pusillin"] = true,
		["Pyroguard Emberseer"] = true,
		["Ramstein the Gorger"] = true,
		["Ras Frostwhisper"] = true,
		["Rattlegore"] = true,
		["Razorlash"] = true,
		["Warchief Rend Blackhand"] = true,
		["Ribbly Screwspigot"] = true,
		["Rotgrip"] = true,
		["Seeth'rel"] = true,
		["Shade of Eranikus"] = true,
		["Shadow Hunter Vosh'gajin"] = true,
		["Solakar Flamewreath"] = true,
		["Stomper Kreeg"] = true,
		["Tendris Warpwood"] = true,
		["The Beast"] = true,
		["The Ravenian"] = true,
		["Timmy the Cruel"] = true,
		["Tinkerer Gizlock"] = true,
		["Tsu'zee"] = true,
		["Vectus"] = true,
		["Vile'rel"] = true,
		["War Master Voone"] = true,
		["Weaver"] = true,
		["Zevrim Thornhoof"] = true,
		["Zolo"] = true,
		["Zul'Lor"] = true,
		
		-- From Mendeleev
		["Cho'Rush the Observer"] = true,
		["Lord Hel'nurath"] = true,
		["Pimgib"] = true,
		["Knot Thimblejack's Cache"] = true,
		["Cannonmaster Willey"] = true,
		["Emperor Dagran Thaurissian"] = true,
		["Archmage Arugal"] = true,
		["Archmage Arugal's Voidwalker"] = true,
		["Baron Silverlaine"] = true,
		["Commander Springvale"] = true,
		["Deathsworn Captain"] = true,
		["Fenrus the Devourer"] = true,
		["Odo the Blindwatcher"] = true,
		["Razorclaw the Butcher"] = true,
		["Wolf Master Nandos"] = true,
		["Rend Blackhand"] = true,
		["Kurinnaxx"] = true,
            
		["Maur Grimtotem"] = true,
		["Oggleflint"] = true,
		["Taragaman the Hungerer"] = true,
		["Jergosh the Invoker"] = true,
		["Bazzalan"] = true,
		["Disciple of Naralex"] = true,
		["Lord Cobrahn"] = true,
		["Lady Anacondra"] = true,
		["Kresh"] = true,
		["Lord Pythas"] = true,
		["Skum"] = true,
		["Lord Serpentis"] = true,
		["Verdan the Everliving"] = true,
		["Verdan the Everliving"] = true,
		["Mutanus the Devourer"] = true,
		["Naralex"] = true,
		["Deviate Faerie Dragon"] = true,
		["Ghamoo-ra"] = true,
		["Lady Sarevess"] = true,
		["Gelihast"] = true,
		["Lorgus Jett"] = true,
		["Baron Aquanis"] = true,
		["Twilight Lord Kelris"] = true,
		["Old Serra'kis"] = true,
		["Aku'mai"] = true,
		["Roogug"] = true,
		["Aggem Thorncurse"] = true,
		["Death Speaker Jargba"] = true,
		["Overlord Ramtusk"] = true,
		["Agathelos the Raging"] = true,
		["Blind Hunter"] = true,
		["Charlga Razorflank"] = true,
		["Earthcaller Halmgar"] = true,
		["Tuten'kash"] = true,
		["Lady Falther'ess"] = true,
		["Mordresh Fire Eye"] = true,
		["Glutton"] = true,
		["Ragglesnout"] = true,
		["Amnennar the Coldbringer"] = true,
		["Plaguemaw the Rotting"] = true,
		["Antu'sul"] = true,
		["Witch Doctor Zum'rah"] = true,
		["Shadowpriest Sezz'ziz"] = true,
		["Gahz'rilla"] = true,
		["Chief Ukorz Sandscalp"] = true,
		["Ruuzlu"] = true,
		["Isalien"] = true,
		["Revanchion"] = true,
		["Lord Roccor"] = true,
		["Anub'shiah"] = true,
		["Eviscerator"] = true,
		["Gorosh the Dervish"] = true,
		["Grizzle"] = true,
		["Hedrum the Creeper"] = true,
		["Ok'thor the Breaker"] = true,
		["Houndmaster Grebmar"] = true,
		["Pyromancer Loregrain"] = true,
		["Warder Stilgiss"] = true,
		["Verek"] = true,
		["Watchman Doomgrip"] = true,
		["Panzor the Invincible"] = true,
		["Mor Grayhoof"] = true,
		["Bannok Grimaxe"] = true,
		["Urok Doomhowl"] = true,
		["Quartermaster Zigris"] = true,
		["Gizrul the Slavener"] = true,
		["Ghok Bashguud"] = true,
		["Jed Runewatcher"] = true;
		["Lord Valthalak"] = true;
		["Grubbis"] = true;
		["Chomper"] = true;
		["Viscous Fallout"] = true;
		["Electrocutioner 6000"] = true;
		["Crowd Pummeler 9-60"] = true;
		["Dark Iron Ambassador"] = true;
		["Mekgineer Thermaplugg"] = true;
		["Houndmaster Loksey"] = true;
		["Arcanist Doan"] = true;
		["Herod"] = true;
		["High Inquisitor Fairbanks"] = true;
		["Scarlet Commander Mograine"] = true;
		["High Inquisitor Whitemane"] = true;
		["Interrogator Vishas"] = true;
		["Bloodmage Thalnos"] = true;
		["Ironspine"] = true;
		["Azshir the Sleepless"] = true;
		["Fallen Champion"] = true;
		["Lord Blackwood"] = true;
		["Death Knight Darkreaver"] = true;
		["Kormok"] = true;
		["Skul"] = true;
		["Balzaphon"] = true;
		["Malor the Zealous"] = true;
		["Sothos"] = true;
		["Jarien"] = true;
		["Stonespine"] = true;
		["Rhahk'Zor"] = true;
		["Miner Johnson"] = true;
		["Sneed"] = true;
		["Gilnid"] = true;
		["Captain Greenskin"] = true;
		["Edwin VanCleef"] = true;
		["Mr. Smite"] = true;
		["Cookie"] = true;
		["Targorr the Dread"] = true;
		["Kam Deepfury"] = true;
		["Hamhock"] = true;
		["Bazil Thredd"] = true;
		["Dextren Ward"] = true;
		["Bruegal Ironknuckle"] = true;
		["Baelog"] = true;
		["Eric \"The Swift\""] = true;
		["Olaf"] = true;
		["Revelosh"] = true;
		["Ironaya"] = true;
		["Obsidian Sentinel"] = true;
		["Ancient Stone Keeper"] = true;
		["Galgann Firehammer"] = true;
		["Grimlok"] = true;
		["Archaedas"] = true;
		["Sever"] = true;
		["Scorn"] = true;
		["Rethilgore"] = true;
		["Atiesh"] = true;
		["Stratholme Courier"] = true;
		["Ancient Core Hound"] = true;
		["Gurubashi Berserker"] = true;
		["Gurubashi Bat Rider"] = true;
		["Elder Mottled Boar"] = true,
		["Gargoyle"] = true,
		["Alterac Valley"] = true,
		["Arathi Basin"] = true
}

print(generateLocalizationTables(originalBossKeys))